loading app ryu_app.py
loading app ryu.controller.ofp_handler
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu_app.py of CertRyuController
Initialisation du contrôleur CertRyuController...
Initialisation de CertRyuController terminée.
Le contrôleur est prêt à recevoir des connexions...
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu.controller.dpset of DPSet
BRICK CertRyuController
  CONSUMES EventDP
  CONSUMES EventOFPStateChange
  CONSUMES EventOFPPortStatus
  CONSUMES EventOFPEchoRequest
  CONSUMES EventOFPErrorMsg
  CONSUMES EventOFPHello
  CONSUMES EventOFPPacketIn
  CONSUMES EventOFPSwitchFeatures
BRICK ofp_event
  PROVIDES EventOFPStateChange TO {'CertRyuController': {'main'}, 'dpset': {'dead', 'main'}}
  PROVIDES EventOFPPortStatus TO {'CertRyuController': {'main'}, 'dpset': {'main'}}
  PROVIDES EventOFPEchoRequest TO {'CertRyuController': {'main'}}
  PROVIDES EventOFPErrorMsg TO {'CertRyuController': {'main'}}
  PROVIDES EventOFPHello TO {'CertRyuController': {'main'}}
  PROVIDES EventOFPPacketIn TO {'CertRyuController': {'main'}}
  PROVIDES EventOFPSwitchFeatures TO {'CertRyuController': {'config'}, 'dpset': {'config'}}
  CONSUMES EventOFPEchoReply
  CONSUMES EventOFPEchoRequest
  CONSUMES EventOFPErrorMsg
  CONSUMES EventOFPHello
  CONSUMES EventOFPPortDescStatsReply
  CONSUMES EventOFPPortStatus
  CONSUMES EventOFPSwitchFeatures
BRICK dpset
  PROVIDES EventDP TO {'CertRyuController': {'main'}}
  CONSUMES EventOFPStateChange
  CONSUMES EventOFPPortStatus
  CONSUMES EventOFPSwitchFeatures
hub: uncaught exception: Traceback (most recent call last):
  File "/home/mouhcine/Documents/IOTA-SDN-jwt/new_ev/lib/python3.9/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/home/mouhcine/Documents/IOTA-SDN-jwt/new_ev/lib/python3.9/site-packages/ryu/controller/controller.py", line 152, in __call__
    self.server_loop(self.ofp_tcp_listen_port,
  File "/home/mouhcine/Documents/IOTA-SDN-jwt/new_ev/lib/python3.9/site-packages/ryu/controller/controller.py", line 200, in server_loop
    server = StreamServer((CONF.ofp_listen_host,
  File "/home/mouhcine/Documents/IOTA-SDN-jwt/new_ev/lib/python3.9/site-packages/ryu/lib/hub.py", line 127, in __init__
    self.server = eventlet.listen(listen_info)
  File "/home/mouhcine/Documents/IOTA-SDN-jwt/new_ev/lib/python3.9/site-packages/eventlet/convenience.py", line 78, in listen
    sock.bind(addr)
OSError: [Errno 98] Address already in use

loading app ryu_app.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu_app.py of CertRyuController
Initialisation du contrôleur CertRyuController...
Initialisation de CertRyuController terminée.
Le contrôleur est prêt à recevoir des connexions...
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
BRICK CertRyuController
  CONSUMES EventDP
  CONSUMES EventOFPStateChange
  CONSUMES EventOFPPortStatus
  CONSUMES EventOFPEchoRequest
  CONSUMES EventOFPErrorMsg
  CONSUMES EventOFPHello
  CONSUMES EventOFPPacketIn
  CONSUMES EventOFPSwitchFeatures
BRICK dpset
  PROVIDES EventDP TO {'CertRyuController': {'main'}}
  CONSUMES EventOFPStateChange
  CONSUMES EventOFPPortStatus
  CONSUMES EventOFPSwitchFeatures
BRICK ofp_event
  PROVIDES EventOFPStateChange TO {'CertRyuController': {'main'}, 'dpset': {'dead', 'main'}}
  PROVIDES EventOFPPortStatus TO {'CertRyuController': {'main'}, 'dpset': {'main'}}
  PROVIDES EventOFPEchoRequest TO {'CertRyuController': {'main'}}
  PROVIDES EventOFPErrorMsg TO {'CertRyuController': {'main'}}
  PROVIDES EventOFPHello TO {'CertRyuController': {'main'}}
  PROVIDES EventOFPPacketIn TO {'CertRyuController': {'main'}}
  PROVIDES EventOFPSwitchFeatures TO {'CertRyuController': {'config'}, 'dpset': {'config'}}
  CONSUMES EventOFPEchoReply
  CONSUMES EventOFPEchoRequest
  CONSUMES EventOFPErrorMsg
  CONSUMES EventOFPHello
  CONSUMES EventOFPPortDescStatsReply
  CONSUMES EventOFPPortStatus
  CONSUMES EventOFPSwitchFeatures
hub: uncaught exception: Traceback (most recent call last):
  File "/home/mouhcine/Documents/IOTA-SDN-jwt/new_ev/lib/python3.9/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/home/mouhcine/Documents/IOTA-SDN-jwt/new_ev/lib/python3.9/site-packages/ryu/controller/controller.py", line 152, in __call__
    self.server_loop(self.ofp_tcp_listen_port,
  File "/home/mouhcine/Documents/IOTA-SDN-jwt/new_ev/lib/python3.9/site-packages/ryu/controller/controller.py", line 200, in server_loop
    server = StreamServer((CONF.ofp_listen_host,
  File "/home/mouhcine/Documents/IOTA-SDN-jwt/new_ev/lib/python3.9/site-packages/ryu/lib/hub.py", line 127, in __init__
    self.server = eventlet.listen(listen_info)
  File "/home/mouhcine/Documents/IOTA-SDN-jwt/new_ev/lib/python3.9/site-packages/eventlet/convenience.py", line 78, in listen
    sock.bind(addr)
OSError: [Errno 98] Address already in use

